mode: redeem_only                  # full_send（发起跨链-查询vaa-目标链执行） | redeem_only（查询vaa-目标链执行）
wtt_method: transferTokens       # transferTokens | transferTokensWithPayload

dst:                              # 源链配置
  rpc: "https://ethereum-sepolia-rpc.publicnode.com"
  name: "ethereum"
  chain_evm_id: 1002

src:                            # 目标链配置      
  rpc: "https://arbitrum-sepolia.drpc.org"
  name: "arbitrum"
  chain_evm_id: 1003

token:                     # 代币配置 
  address_on_src: "0x7ba1888061E4AF2C0ba504E7d069022F71dBF862"        # 源链代币合约地址
  decimals: 18
  symbol: "TALK"
  approve_required: true          # 是否需要先调用approve，true表示需要授权，授权数量为代币跨链数量，false表示不需要授权

recipient_on_dst: "0x9CAEE92287CAD179541bc7C44874b485b9AaC88b"       # 目标链接收地址（bytes32格式）
amount: "1"                   # 跨链代币数量，十进制字符串

private_key_env: "PRIVATE_KEY"   # .env文件中的变量名

wormholescan_api_base: "https://api.testnet.wormholescan.io/api/v1" #正式网"https://api.wormholescan.io/api/v1"    # wormholescan API
vaa_poll_interval_seconds: 0.1        # VAA轮询间隔（秒）   
vaa_alert_interval_seconds: 60    # VAA告警间隔（秒）
vaa_alert_timeout_seconds: 600    # VAA告警超时（秒），超过该时间未获取到VAA则在日志里打印警告       

token_bridge_contract_src: "0xC7A204bDBFe983FCD8d8E61D02b475D4073fF97e"    # 源链Token Bridge合约地址
token_bridge_contract_dst: "0xDB5492265f6038831E89f495670FF909aDe94bd9"   # 目标链Token Bridge合约地址

log_level: "INFO"

# 可选：transferTokensWithPayload模式下的payload（16进制字符串，例："0x1234abcd"）
payload: ""

# redeem_only模式下需要指定源链跨链交易哈希
src_tx_hash: "0x4f84bb5bb79ea16d339d5d279918a01219706a0341fe7c4c8f05eab048b5201b"
