# 正式网DAO代币从BSC跨链到BASE

mode: full_send                  # full_send（发起跨链-查询vaa-目标链执行） | redeem_only（查询vaa-目标链执行）
wtt_method: transferTokens       # transferTokens | transferTokensWithPayload

src:                              # 源链配置
  rpc: "https://bsc-rpc.publicnode.com"
  name: "BNB Smart Chain"
  wormhole_evm_id: 4      # 虫洞链id
  is_poa: true  #POA链(BSC、Moonbeam、Evmos、XRPL-EVM、HyperEVM)，需要中间件
token_bridge_contract_src: "0xB6F6D86a8f9879A9c87f643768d9efc38c1Da6E7"    # 源链Token Bridge合约地址

dst:                            # 目标链配置      
  rpc: "https://base-rpc.publicnode.com"
  name: "Base"
  wormhole_evm_id: 30     # 虫洞链id
  is_poa: false  # POA链，需要中间件
token_bridge_contract_dst: "0x8d2de8d2f73F1F4cAB472AC9A881C9b123C79627"   # 目标链Token Bridge合约地址  

token:                     # 代币配置 
  address_on_src: "0x4d2d32d8652058Bf98c772953E1Df5c5c85D9F45"        # 源链代币合约地址
  decimals: 18
  symbol: "DAO"
  approve_required: true          # 是否需要先调用approve，true表示需要授权，授权数量为代币跨链数量，false表示不需要授权
  wormhole_declaims: 8 # Wormhole declaims 数量（通常为8），用于校验VAA

recipient_on_dst: "0x9CAEE92287CAD179541bc7C44874b485b9AaC88b"       # 目标链接收地址（bytes32格式）
amount: "0.3"                   # 跨链代币数量，十进制字符串

private_key_env: "PRIVATE_KEY"   # .env文件中的变量名

wormholescan_api_base: "https://api.wormholescan.io/api/v1"    # wormholescan API
vaa_poll_interval_seconds: 0.1        # VAA轮询间隔（秒）   
vaa_alert_interval_seconds: 60    # VAA告警间隔（秒）
vaa_alert_timeout_seconds: 600    # VAA告警超时（秒），超过该时间未获取到VAA则在日志里打印警告       

log_level: "INFO"

# 可选：transferTokensWithPayload模式下的payload（16进制字符串，例："0x1234abcd"）
payload: ""

# redeem_only模式下需要指定源链跨链交易哈希
src_tx_hash: "0x0ac6fb99ee05c269c1ac67ab8fe01081725249f487b259c60cdcf8d6b008fcd6"